### ISSUE TITLE
Make sign.php usable

### ISSUE THREAD

**Issue by ShAd0wInK** [ShAd0wInK/SI-Space#13]
**Goal :**
* Create *sign in* and *sign up* system

**Comment by WebFaker** [comment]
Just need to modify the redirections stuff etc and everything's good ![bitmoji](https://render.bitstrips.com/v2/cpanel/6cd83ca1-68db-4dfb-a0e5-ca72d017a5b2-1a4b1474-2fba-4a72-a82c-d2ad1368f33b-v1.png?transparent=1&palette=1&width=246)
