### ISSUE TITLE
Starting Main Page integration

### ISSUE THREAD

**Issue by WebFaker** [ShAd0wInK/SI-Space#28]
We need to do the **Main Page**. 
![bitmoji](https://render.bitstrips.com/v2/cpanel/4fd49c6c-ce25-458f-9b32-eaea541f1922-1a4b1474-2fba-4a72-a82c-d2ad1368f33b-v1.png?transparent=1&palette=1&width=246)

**Comment by ShAd0wInK** [comment]
WIP, landing page + who + packs in progress
